### PR TITLE
Properly handle encrypted LZFSE-compressed IM4P payloads

### PR DESCRIPTION
**Pull request by m1stadev**

### CODE REVIEW

**Comment by m1stadev** [comment]
@doronz88 \*finally* got around to finishing this PR, could you try it out?

**Comment by doronz88** [comment]
I'm missing the length field from the IM4P when trying to send the iBEC.
This is the code I used:

```python
im4p = pyimg4.IM4P(data=data)
img4 = pyimg4.IMG4(im4p=data, im4m=blob).output()
```

When examining the `im4p` object, it seems the compression is: `Compression.UNKNOWN`.
```python3
print(im4p) # IM4P(fourcc=ibec, description="iBoot-8419.40.112")
print(im4p.payload.compression) # Compression.UNKNOWN
```

**Comment by doronz88** [comment]
I think another enum member is the best for it - but still, what interface will allow adding the size field for those components?  Can it be parsed directly when I pass the `data`?

**Comment by m1stadev** [comment]
> I think another enum member is the best for it - but still, what interface will allow adding the size field for those components? Can it be parsed directly when I pass the `data`?

If you pass an encrypted+LZFSE-compressed IM4P, it will parse and store the uncompressed size automatically. If you passed only the encrypted+LZFSE-compressed data, you would need to manually specify the size (by setting `IM4PData.lzfse_payload_size`), and the keybags (by appending `Keybag` objects to `IM4PData.keybags` (Come to think of it, I need to add methods for adding/removing keybags and make `IM4PData.keybags` private sometime.)), then create an IM4P.

**Comment by m1stadev** [comment]
@doronz88 Also, could you DM me the iBEC you're using to test via Discord (m1sta#9999) please?

**Pull request merged**
